# Generated by Django 2.0.1 on 2018-04-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='team_number',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_number',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
