# Generated by Django 2.0.1 on 2018-04-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180423_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
