# Generated by Django 2.0.1 on 2018-04-23 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180423_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Team'),
        ),
    ]
