# Generated by Django 2.0.1 on 2018-04-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180423_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-user',)},
        ),
        migrations.AlterField(
            model_name='profile',
            name='team_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
