# Generated by Django 2.0.1 on 2018-05-04 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='student_number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='major',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='team_number',
        ),
    ]
