# Generated by Django 2.0.1 on 2018-05-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_team_number_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
