# Generated by Django 2.0.1 on 2018-05-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_team_number_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['team_number']},
        ),
        migrations.RemoveField(
            model_name='team',
            name='number_team',
        ),
    ]
