# Generated by Django 2.0.1 on 2018-05-06 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20180505_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Team'),
        ),
    ]
