# Generated by Django 2.0.1 on 2018-03-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflection', '0003_auto_20180322_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='student_name',
        ),
        migrations.AddField(
            model_name='reflection',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
