# Generated by Django 2.0.1 on 2018-04-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Web Application', 'Web Application'), ('Mobile Application', 'Mobile Application'), ('Software', 'Software'), ('Hardware', 'Hardware'), ('Data', 'Data')], max_length=1),
        ),
    ]
