# Generated by Django 2.0.1 on 2018-04-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20180423_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Web Application', 'Web Application'), ('Mobile Application', 'Mobile Application'), ('Software', 'Software'), ('Hardware', 'Hardware'), ('Data', 'Data')], max_length=20),
        ),
    ]
