# Generated by Django 2.0.1 on 2018-04-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved_comment',
            field=models.BooleanField(default=False),
        ),
    ]
