# Generated by Django 2.0.1 on 2018-03-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20180307_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='document',
            field=models.FileField(blank=True, upload_to='project/documents/%Y/%m'),
        ),
    ]
