# Generated by Django 2.0.1 on 2018-04-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_assignment_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='document',
            field=models.FileField(blank=True, upload_to='assignment/documents/%Y/%m'),
        ),
    ]
